namePrefix: staging-
forceCommonAnnotations: true
commonAnnotations:
  elestyle/app-version: ${ARGOCD_APP_REVISION_SHORT}
commonLabels:
  variant: staging
bases:
- ../../base
patchesStrategicMerge:
- config-map.yaml
