namePrefix: staging-
commonAnnotations:
  elestyle/app-version: 2024-04-05-03
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    variant: staging
patches:
- path: config-map.yaml
